//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
// 


/// <comentarios/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DSDetalleXGuia.xsd")]
public partial class DSDetalleXGuia {
    
    private DSDetalleXGuiaBARRAS[] itemsField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("BARRAS")]
    public DSDetalleXGuiaBARRAS[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DSDetalleXGuia.xsd")]
public partial class DSDetalleXGuiaBARRAS {
    
    private int idField;
    
    private string cODIGOField;
    
    private int iD_GUIA_DESPACHO_DETALLEField;
    
    private int cANTIDADField;
    
    private bool cANTIDADFieldSpecified;
    
    private int cANTIDAD_TOTALField;
    
    private bool cANTIDAD_TOTALFieldSpecified;
    
    private int nUMERO_GUIAField;
    
    private bool nUMERO_GUIAFieldSpecified;
    
    private string rUT_PROVEEDORField;
    
    private int lINEAField;
    
    private bool lINEAFieldSpecified;
    
    /// <comentarios/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public string CODIGO {
        get {
            return this.cODIGOField;
        }
        set {
            this.cODIGOField = value;
        }
    }
    
    /// <comentarios/>
    public int ID_GUIA_DESPACHO_DETALLE {
        get {
            return this.iD_GUIA_DESPACHO_DETALLEField;
        }
        set {
            this.iD_GUIA_DESPACHO_DETALLEField = value;
        }
    }
    
    /// <comentarios/>
    public int CANTIDAD {
        get {
            return this.cANTIDADField;
        }
        set {
            this.cANTIDADField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CANTIDADSpecified {
        get {
            return this.cANTIDADFieldSpecified;
        }
        set {
            this.cANTIDADFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CANTIDAD_TOTAL {
        get {
            return this.cANTIDAD_TOTALField;
        }
        set {
            this.cANTIDAD_TOTALField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CANTIDAD_TOTALSpecified {
        get {
            return this.cANTIDAD_TOTALFieldSpecified;
        }
        set {
            this.cANTIDAD_TOTALFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int NUMERO_GUIA {
        get {
            return this.nUMERO_GUIAField;
        }
        set {
            this.nUMERO_GUIAField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NUMERO_GUIASpecified {
        get {
            return this.nUMERO_GUIAFieldSpecified;
        }
        set {
            this.nUMERO_GUIAFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string RUT_PROVEEDOR {
        get {
            return this.rUT_PROVEEDORField;
        }
        set {
            this.rUT_PROVEEDORField = value;
        }
    }
    
    /// <comentarios/>
    public int LINEA {
        get {
            return this.lINEAField;
        }
        set {
            this.lINEAField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LINEASpecified {
        get {
            return this.lINEAFieldSpecified;
        }
        set {
            this.lINEAFieldSpecified = value;
        }
    }
}
